### ISSUE TITLE
Kinect Camera Doesn't Show Up in /dev

### ISSUE THREAD

**Issue by ghost** [xxorde/librekinect#2]
Hello,

I'm trying to get your driver to work on a RPi running Arch Linux ARM. The driver compiles and loads fine, but I get no /dev/video*. lsusb seems to only show the motor connected:

```
$ lsusb
Bus 001 Device 006: ID 045e:02b0 Microsoft Corp. Xbox NUI Motor
Bus 001 Device 005: ID 0409:005a NEC Corp. HighSpeed Hub
Bus 001 Device 004: ID 2109:3431
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9512 Standard Microsystems Corp. SMC9512/9514 USB Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

From the OpenKinect wiki, I think this is normal and I just need to activate the motor to get the other two devices to appear underneath that hub, but how should I go about this? Is there a libusb driver from libfreenect that I need to use?

**Comment by Lauraortizrd** [comment]
I had exactly the same error. The problem is in the charger that powers the device. You can try checking the connection of the source or the cable responsible for charging the device..
the only device it detects is the motor, which is powered by 5v directly from the computer it is connected to, but the camera is powered by the charger.
